### ISSUE TITLE
弱弱的问一句，大概需要什么水平才能参与到这个项目中来？

### ISSUE THREAD

**Issue by huntdream** [yangfan0095/guwen-spider#3]

**Comment by yangfan0095** [comment]
我主观的认为 前端最大的挑战不在于你当下你会多少个框架，熟悉多少个类库，而是保持一种不断向前的态度，和一种开放的心态。如果后者能做到，我们就很欢迎你。
我们guwenlab 开源团队的宗旨就是 ，使用各种技术来持续打造一个最佳体验的开源社区。这个社区对技术爱好者就像是一个平台，可以随便做尝试，搞事情😉。

**Comment by huntdream** [comment]
只有不断向前才能看到新的风景，作为一只初出茅庐的前端菜鸟没有理由不往前走。前端的开放是吸引我走向前端的一个主要原因，我也从中受益匪浅！我想加入你们有几个原因：
- 学习
- 贡献代码
- 喜欢古文、诗词

我觉得这个项目很适合我，前端我所欲也，古文亦我所欲也，二者似乎可以得兼？

毕竟我是一个尚未找过工作的前端菜鸟，很多东西可能不会，会的东西可能也不够深入，所以我很想真正参与到这个项目中来做点事情贡献社区、提升自己，
😄
